image: node

before_script:
  - npm i -g firebase-tools

deploy:
  stage: deploy
  script:
    - echo "---installing node modules"
    - npm install
    - echo "---install done"
    - echo "---firebase login"
    - firebase login
    - echo "---deploy starting"
    - firebase deploy
