image: node

before_script:
  - npm i -g firebase-tools

deploy:
  stage: deploy
  script:
    - echo "---installing node modules"
    - npm install
    - echo "---install done"
    - echo "building"
    - npm run build
    - echo "---deploy starting"
    - firebase deploy --token "1//0epcFg683HJPgCgYIARAAGA4SNwF-L9IrqYkAcN6lSSug046OMKNx3K5FkBeHpbLuhMpXqGiYDeg20o3ZeJXf5M8N2ZWBVYTvyfI"
